[build]
command = "npm run build"
publish = "dist"
node_bundler = "npm"

[build.environment]
NODE_VERSION = "18.20.0"
NPM_VERSION = "9.8.1"

[context.production]
command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
